source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'rails-api'

gem 'sqlite3'

gem 'devise'

group :test do
  gem 'shoulda-matchers'
end

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
end

group :development do
  gem 'guard-rspec'
  gem 'pry-debugger', github: 'nixme/pry-debugger'
end
